# 1) Numpy Array

## Array Basics

1D Array

In [214]:
import numpy as np

In [215]:
my_list = [1,2,3,4,5]
print(my_list)

[1, 2, 3, 4, 5]


In [216]:
np.array(my_list)

array([1, 2, 3, 4, 5])

In [217]:
arr = np.array(my_list)

In [218]:
arr

array([1, 2, 3, 4, 5])

2D Array

In [219]:
my_mat = [[1,2,3], [4,5,6], [7,8,9]]

In [220]:
my_mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [221]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Numpy arrays using built methods

In [222]:
import numpy as np

Arrange

In [223]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [224]:
np.arange(0,11,2) # just odd

array([ 0,  2,  4,  6,  8, 10])

Zeros

In [225]:
np.zeros(3) # array of size 3 filled of 0

array([0., 0., 0.])

In [226]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

Ones

In [227]:
np.ones(20)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

In [228]:
np.ones((2,7))

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

Linspace

In [229]:
np.linspace(0,5,10) # from 0 to 5 get10 numbers

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [230]:
np.linspace(0,5,15)

array([0.        , 0.35714286, 0.71428571, 1.07142857, 1.42857143,
       1.78571429, 2.14285714, 2.5       , 2.85714286, 3.21428571,
       3.57142857, 3.92857143, 4.28571429, 4.64285714, 5.        ])

Eye

In [231]:
np.eye(5) # only diagonal

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

Array of random number between 0 to 1

In [232]:
np.random.rand(5)

array([0.42494415, 0.91023454, 0.29671089, 0.54414494, 0.81435403])

In [233]:
np.random.rand(4,4)

array([[0.47544566, 0.40609776, 0.35876776, 0.04531286],
       [0.35220372, 0.81858411, 0.23507036, 0.72969885],
       [0.92684754, 0.05737002, 0.31209684, 0.65816924],
       [0.12826368, 0.93930303, 0.2349364 , 0.46977653]])

Gaussian distribution or Standard normal distribution

In [234]:
np.random.randn(4)

array([-0.59656916,  0.09946957,  0.6508337 ,  2.44845565])

In [235]:
np.random.randn(4,5)

array([[-0.00979201, -1.59708676,  1.09045897,  1.21246674, -1.97889624],
       [ 0.04022407,  0.40780882,  1.67869785, -0.29526081,  0.70383922],
       [-0.06422255,  0.64579613, -0.42104273, -0.03445603,  0.34247149],
       [ 0.68479877,  0.16729078, -1.75416638, -1.04544738, -0.53747471]])

Randint

In [236]:
np.random.randint(0,100) # 0 included, 100 excluded

95

In [237]:
np.random.randint(0,100,10)

array([38, 25, 23, 17, 41,  4, 66,  1, 27, 51])

## Usefull attributes and methods

In [238]:
arr = np.arange(25)

In [239]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

Reshape

In [240]:
arr.reshape(5,5) # 1D array to 2D array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [241]:
# arr.reshape(5,10) # BEEEEN

Max, Min

In [242]:
ran_arr = np.random.randint(0,50,10)

In [243]:
ran_arr

array([42, 18,  4,  3, 44, 10, 42, 23, 16,  1])

In [244]:
ran_arr.max()

44

In [245]:
ran_arr.min()

1

In [246]:
ran_arr.argmax() # position of max

4

In [247]:
ran_arr.argmin() # position of min

9

Shape

In [248]:
arr.shape

(25,)

In [249]:
b = arr.reshape(5,5)

In [250]:
b.shape

(5, 5)

Dtype

In [251]:
arr.dtype # data type

dtype('int64')

# 2) Numpy Indexing and Selection

## Indexing and Selection Basics

In [252]:
import numpy as np

In [253]:
arr = np.arange(10,21)

In [254]:
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [255]:
arr[5]

15

In [256]:
arr[0:5]

array([10, 11, 12, 13, 14])

In [257]:
arr[2:]

array([12, 13, 14, 15, 16, 17, 18, 19, 20])

In [258]:
arr[:6]

array([10, 11, 12, 13, 14, 15])

## Broadcasting the values

In [259]:
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [260]:
arr[0:5] = 100

In [261]:
arr

array([100, 100, 100, 100, 100,  15,  16,  17,  18,  19,  20])

In [262]:
arr = np.arange(10,21)

In [263]:
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [264]:
slice_arr = arr[0:6]

In [265]:
slice_arr

array([10, 11, 12, 13, 14, 15])

In [266]:
slice_arr[:] = 99

In [267]:
slice_arr # data is not copied

array([99, 99, 99, 99, 99, 99])

In [268]:
arr

array([99, 99, 99, 99, 99, 99, 16, 17, 18, 19, 20])

Realy copy an array

In [269]:
arr_cp = arr.copy()

In [270]:
arr_cp

array([99, 99, 99, 99, 99, 99, 16, 17, 18, 19, 20])

In [271]:
arr[:] = 100

In [272]:
arr_cp

array([99, 99, 99, 99, 99, 99, 16, 17, 18, 19, 20])

In [273]:
arr

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

---

In [274]:
arr = np.arange(0,11)

In [275]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [276]:
slice_2 = arr[0:5]

In [277]:
slice_2

array([0, 1, 2, 3, 4])

In [278]:
slice_2[:] = 100

In [279]:
slice_2

array([100, 100, 100, 100, 100])

In [280]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [281]:
arr_cp2 = arr.copy()

In [282]:
arr_cp2[:] = 200

In [283]:
arr_cp2

array([200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200])

In [284]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

## Indexing a 2D array (Matrix)

In [285]:
import numpy as np

In [286]:
arr_2d = np.array([[5,10,15], [20,25,30], [35,40,45]])

In [287]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [288]:
arr_2d[0, 0]

5

In [289]:
arr_2d[1,0]

20

In [290]:
arr_2d[0:2, 1:3]

array([[10, 15],
       [25, 30]])

## Conditional Selection

In [291]:
arr = np.arange(0,11)

In [292]:
arr > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [293]:
b = arr > 5

In [294]:
b

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [295]:
arr[b]

array([ 6,  7,  8,  9, 10])

In [296]:
arr[arr < 8]

array([0, 1, 2, 3, 4, 5, 6, 7])

# 3) Numpy Operations

In [297]:
import numpy as np

Array with array

In [298]:
arr = np.arange(0,11)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [299]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [300]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [301]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [302]:
arr / arr

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

Array with scalar

In [303]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [304]:
arr - 50

array([-50, -49, -48, -47, -46, -45, -44, -43, -42, -41, -40])

In [305]:
arr * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [306]:
arr / 2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [307]:
1/arr

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [308]:
arr**2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [309]:
arr**3

array([   0,    1,    8,   27,   64,  125,  216,  343,  512,  729, 1000])

Universal array functions

In [310]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [311]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [312]:
np.max(arr)

10

In [313]:
np.min(arr)

0

In [314]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [315]:
np.log(arr)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])