# IMDB, Amazon and Yelp review Classification with SpaCy


## 1) Importing the datasets

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
data_yelp = pd.read_csv(
    '/content/drive/MyDrive/Colab Notebooks/NLP/IMDB, Amazon and Yelp review Classification/yelp_labelled.txt',
    sep='\t', header=None)

In [ ]:
data_yelp.head()
# 0 - Negative
# 1 - Positive

0  1
0                           Wow... Loved this place.  1
1                                 Crust is not good.  0
2          Not tasty and the texture was just nasty.  0
3  Stopped by during the late May bank holiday of...  1
4  The selection on the menu was great and so wer...  1

In [ ]:
column_name = ['Review', 'Sentiment']
data_yelp.columns = column_name

In [ ]:
data_yelp.head()

Review  Sentiment
0                           Wow... Loved this place.          1
1                                 Crust is not good.          0
2          Not tasty and the texture was just nasty.          0
3  Stopped by during the late May bank holiday of...          1
4  The selection on the menu was great and so wer...          1

In [ ]:
data_yelp.shape

(1000, 2)

In [ ]:
data_amazon = pd.read_csv(
    '/content/drive/MyDrive/Colab Notebooks/NLP/IMDB, Amazon and Yelp review Classification/amazon_cells_labelled.txt', 
    sep='\t', header=None)

data_amazon.head()
# 0 - Negative
# 1 - Positive

0  1
0  So there is no way for me to plug it in here i...  0
1                        Good case, Excellent value.  1
2                             Great for the jawbone.  1
3  Tied to charger for conversations lasting more...  0
4                                  The mic is great.  1

In [ ]:
data_amazon.columns = column_name

In [ ]:
data_amazon.head()

Review  Sentiment
0  So there is no way for me to plug it in here i...          0
1                        Good case, Excellent value.          1
2                             Great for the jawbone.          1
3  Tied to charger for conversations lasting more...          0
4                                  The mic is great.          1

In [ ]:
data_amazon.shape

(1000, 2)

In [ ]:
data_imdb = pd.read_csv(
    '/content/drive/MyDrive/Colab Notebooks/NLP/IMDB, Amazon and Yelp review Classification/imdb_labelled.txt', 
    sep='\t', header=None)

data_imdb.head()
# 0 - Negative
# 1 - Positive

0  1
0  A very, very, very slow-moving, aimless movie ...  0
1  Not sure who was more lost - the flat characte...  0
2  Attempting artiness with black & white and cle...  0
3       Very little music or anything to speak of.    0
4  The best scene in the movie was when Gerardo i...  1

In [ ]:
data_imdb.columns = column_name

In [ ]:
data_imdb.head()

Review  Sentiment
0  A very, very, very slow-moving, aimless movie ...          0
1  Not sure who was more lost - the flat characte...          0
2  Attempting artiness with black & white and cle...          0
3       Very little music or anything to speak of.            0
4  The best scene in the movie was when Gerardo i...          1

In [ ]:
data_imdb.shape

(748, 2)

Agroup all datasets in one

In [ ]:
data = data_yelp.append([data_amazon, data_imdb], ignore_index=True)

In [ ]:
data.shape

(2748, 2)

In [ ]:
data.head()

Review  Sentiment
0                           Wow... Loved this place.          1
1                                 Crust is not good.          0
2          Not tasty and the texture was just nasty.          0
3  Stopped by during the late May bank holiday of...          1
4  The selection on the menu was great and so wer...          1

In [ ]:
data['Sentiment'].value_counts()
# 1386 reviews positivos
# 1362 reviews negativos

1    1386
0    1362
Name: Sentiment, dtype: int64

In [ ]:
data.isnull().sum()
#  Sem valores NULL

Review       0
Sentiment    0
dtype: int64

In [ ]:
x = data['Review']
y = data['Sentiment']

## 2) Data Cleaning

*   Remove Stopwords
*   Remove punctuations
*   Lemmatization



In [46]:
import string

In [47]:
punct = string.punctuation

In [48]:
punct

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [49]:
from spacy.lang.en.stop_words import STOP_WORDS

In [51]:
stopwords = list(STOP_WORDS) # list with all the stop words

In [52]:
print(stopwords)

['themselves', 'last', 'onto', 'would', 'mostly', 'same', 'throughout', 'any', 'noone', 'does', 'in', 'also', 'fifty', 'nowhere', 'from', 'since', 'either', 'therefore', 'he', 'always', 'they', 'whereupon', 'afterwards', 'other', 'say', 'to', 'per', 'thereupon', 'keep', 'become', 'latter', 'then', 'wherever', 'ours', 'have', 'hundred', 'it', 'alone', 'already', 'below', 'ca', 'four', 'often', 'regarding', 'eleven', 'quite', 'seeming', 'because', 'into', 'really', 'so', 'do', 'made', 'out', 'together', 'unless', "'ve", 'nor', 'former', 'my', 'myself', 'top', 'has', 'most', 'this', '’re', 'his', 'due', 'therein', 'done', 'you', 'could', 'now', 'am', 'latterly', 'thru', '’s', 'first', 'along', 'all', 'while', 'except', 'been', '‘ve', 'anyhow', 'still', 'across', 'call', 'hereupon', "'ll", 'mine', 'see', 'us', '‘m', 'should', 'became', 'yourselves', 'himself', 'further', 'very', 'yet', 'if', '’d', 'everywhere', 'anything', 'before', 'a', 'neither', 'beforehand', 'yourself', 'ever', 'whenev

In [65]:
import spacy
nlp = spacy.load('en_core_web_sm')

In [66]:
def text_data_cleaning(sentence):
  doc = nlp(sentence)

  tokens = [] # list of tokens
  for token in doc:
    if token.lemma_ != "-PRON-":  # Se não for pronome
      temp = token.lemma_.lower().strip()
    else: #  Se for, já está na forma orignal
      temp = token.lower_
    tokens.append(temp)

  cleaned_tokens = []
  for token in tokens:
    if token not in stopwords and token not in punct:
      cleaned_tokens.append(token)
  return cleaned_tokens

In [69]:
text_data_cleaning("Hello all of you, It´s a beautiful day outside there!")

['hello', 'it´s', 'beautiful', 'day', 'outside']

## Vectorization Feature Engineering (TF-IDF)

-> term frequency - inverse document frequency

Classifica uma palavra baseado no quanto ela aparece no documento com a quantidae de documentos que ela aparece

*   Palavras raras terão pontuação mais alta
*   Palavras comuns terão pontuação mais baixa

In [70]:
from sklearn.svm import LinearSVC
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.pipeline import Pipeline

In [73]:
tfidf = TfidfVectorizer(tokenizer=text_data_cleaning)
# Tokenization será feito a partir da função 'text_data_cleaning' e depois fará o TF-IDF

In [75]:
classifier = LinearSVC()

## 3) Train the Model

In [76]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=0)  # 20% para teste

In [78]:
x_train.shape, y_test.shape

((2198,), (550,))

In [79]:
x_train.head()

2572    An Italian reviewer called this "a small, grea...
526                          And it was way to expensive.
1509    As an earlier review noted, plug in this charg...
144     Nice blanket of moz over top but i feel like t...
2483    The film gives meaning to the phrase, "Never i...
Name: Review, dtype: object

### Fit the x_train and y_train

In [82]:
clf = Pipeline([('tfidf', tfidf), ('clf', classifier)])  #  clf possivel relacionamento com supor vector machine svm
# first do : Vectorization // second do : classification

In [81]:
clf.fit(x_train, y_train)

Pipeline(memory=None,
         steps=[('tfidf',
                 TfidfVectorizer(analyzer='word', binary=False,
                                 decode_error='strict',
                                 dtype=<class 'numpy.float64'>,
                                 encoding='utf-8', input='content',
                                 lowercase=True, max_df=1.0, max_features=None,
                                 min_df=1, ngram_range=(1, 1), norm='l2',
                                 preprocessor=None, smooth_idf=True,
                                 stop_words=None, strip_accents=None,
                                 sublinear_tf=False,
                                 token_pattern='(?u)\\b\\w\\w+\\b',
                                 tokenizer=<function text_data_cleaning at 0x7f4d12787730>,
                                 use_idf=True, vocabulary=None)),
                ('clf',
                 LinearSVC(C=1.0, class_weight=None, dual=True,
                           fit_intercept

## 4) Predict the Test set results

In [83]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [84]:
y_pred = clf.predict(x_test)

In [88]:
confusion_matrix(y_test, y_pred)

# acertou 201 errou 78
# errou 50 acertou 221

array([[201,  78],
       [ 50, 221]])

In [90]:
print(classification_report(y_test, y_pred))

# 77% de acuracia :P

              precision    recall  f1-score   support

           0       0.80      0.72      0.76       279
           1       0.74      0.82      0.78       271

    accuracy                           0.77       550
   macro avg       0.77      0.77      0.77       550
weighted avg       0.77      0.77      0.77       550



In [91]:
accuracy_score(y_test, y_pred)

# 76% de acuracia

0.7672727272727272

In [105]:
clf.predict(['Wow, I am learning Natural Language Processing in fun fashion'])
# 1 == Positive

array([1])

In [106]:
clf.predict(['It´s hard to learn new things'])
# 0 == Negative

array([0])